# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/arjun27799/Question-Answering-model-using-transformers/blob/master/question-answering%20model.ipynb
"""

pip install transformers

import torch

from transformers import BertForQuestionAnswering

model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

def answer_question(question):
    
    answer_text = """His joint records of beating 21 boxers for the world heavyweight title and winning 14 unified title bouts stood for 35 years. 
    He remained an active public figure globally but in his later years made increasingly limited public appearances as his condition worsened and 
    he was cared for by his family. In 1984 he made public his diagnosis of Parkinson's disease which some reports attribute to boxing-related injuries
    though he and his specialist physicians disputed this. At 18 he won a gold medal in the light heavyweight division at the 1960 Summer Olympics and 
    turned professional later that year. Ali was arguably the most famous and documented human of the 20th century.Muhammad Ali (/ɑːˈliː/;  born Cassius
    Marcellus Clay Jr.;  January 17 1942 – June 3 2016) was an American professional boxer activist and philanthropist.Ali thrived in the spotlight at a 
    time when many fighters let their managers do the talking and he was often provocative and outlandish. He was famous for trash-talking and often 
    free-styled with rhyme schemes and spoken word poetry anticipating elements of hip hop. He won the  world heavyweight championship from Sonny Liston 
    in a major upset at age 22 in 1964. Ali was born and raised in Louisville Kentucky and began training as an amateur boxer at age 12. Ali was known to 
    be a very generous person who loved attention as well as making other people happy. [note 1] Ali is the only boxer to be named the Ring magazine Fighter
    of the Year six times. He was arrested found guilty of draft evasion and stripped of his boxing titles. Ali also attained success as a musician receiving
    two  Grammy award nominations. In 1966 Ali refused to be drafted into the military citing his religious beliefs and opposition to the Vietnam War.
    He was an ocassional actor and a writer who released two autobiographies. He converted to Islam and became a Muslim after 1961 and eventually took the name
    Muhammad Ali. As a Muslim Ali was initially affiliated with Elijah Muhammad's Nation of Islam (NOI)."""
   
    input_ids = tokenizer.encode(question, answer_text)

   
    print('Query has {:,} tokens.\n'.format(len(input_ids)))

   
    sep_index = input_ids.index(tokenizer.sep_token_id)

    
    num_seg_a = sep_index + 1

   
    num_seg_b = len(input_ids) - num_seg_a

    
    segment_ids = [0]*num_seg_a + [1]*num_seg_b

   
    assert len(segment_ids) == len(input_ids)

    
    start_scores, end_scores = model(torch.tensor([input_ids]), # The tokens representing our input text.
                                    token_type_ids=torch.tensor([segment_ids])) # The segment IDs to differentiate question from answer_text

   
    answer_start = torch.argmax(start_scores)
    answer_end = torch.argmax(end_scores)

    
    tokens = tokenizer.convert_ids_to_tokens(input_ids)

    
    answer = tokens[answer_start]

    
    for i in range(answer_start + 1, answer_end + 1):
        
        
        if tokens[i][0:2] == '##':
            answer += tokens[i][2:]
        
      
        else:
            answer += ' ' + tokens[i]

    print('Answer: "' + answer + '"')

answer_question(" Who was Mohammad Ali?")

answer_question("Where was Mohammad Ali born?")

answer_question("Did Mohammad ali join the military?")







